### ISSUE TITLE
I may have found a new bug.

### ISSUE THREAD

**Issue by algsupport** [tylercollier/openresync#10]
So, I was able to run the project and everything seems to be working great except that it will not fetch any properties.

I have changed the config to this:

```
const rebnyTrestle = {
  getResourceEndpoint: mlsResourceObj => {
    const endpoint = `https://api-prod.corelogic.com/trestle/odata/${mlsResourceObj.name}`
    const url = new URL(endpoint)
    // These can be useful subsets for dev purposes
    // if (mlsResourceObj.name === 'Property') {
    //   url.searchParams.set('$filter', "City eq 'Georgetown'")
    // } else if (mlsResourceObj.name === 'Member') {
    //   url.searchParams.set('$filter', "MemberCity eq 'Georgetown'")
    // }
    return url.toString()
  }
}
```

I am getting an error 400 on the sync step

You can find the logs here:

https://justpaste.it/9r0i6

I tried redacting any sensitive information, I have also removed the data field that contained an encoded numbers array.

This is a screenshot from the user interface.
![image](https://user-images.githubusercontent.com/8190132/148065413-623c8223-55e5-499f-a448-0bfaa9b696b8.png)

Let me know if you need more information on this issue.

Regards

**Comment by algsupport** [comment]
I forgot to put his error here:

```
root@resosyncer:~/openresync# NODE_ENV=production TZ=UTC node server/index.js
🚀 Server listening on port 4000
runningJobsCount 1 Starting job purge rebnyTrestle at 2022-01-04 1:25:00 pm 
-> downloading [========================================] 100% 0.0s
-> downloading [========================================] 100% 0.0s
-> downloading [========================================] 100% 0.0s
runningJobsCount 0 Ended job purge rebnyTrestle at 2022-01-04 1:25:42 pm 
runningJobsCount 1 Starting job reconcile rebnyTrestle at 2022-01-04 1:40:00 pm 
-> downloading [========================================] 100% 0.0s
-> downloading [========================================] 100% 0.0s
-> downloading [========================================] 100% 0.0s
runningJobsCount 0 Ended job reconcile rebnyTrestle at 2022-01-04 1:40:58 pm 
(node:17341) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/root/openresync/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/openresync/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/root/openresync/node_modules/axios/lib/adapters/http.js:231:9)
    at RedirectableRequest.emit (events.js:314:20)
    at RedirectableRequest._processResponse (/root/openresync/node_modules/follow-redirects/index.js:380:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/root/openresync/node_modules/follow-redirects/index.js:56:10)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
(node:17341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tylercollier** [comment]
After talking with the OP, we think this was a temporary hiccup caused by Trestle. Trying again later resolved the HTTP 400 error.
